### ISSUE TITLE
[RFC] Better distribution story for scry

### ISSUE THREAD

**Issue by kofno** [kofno/scry#3]
VSCode packages can't be larger then 20MB. So I can't distribute Cystal-IDE w/ bundled binaries for all platform/arch combos we'll want to support (probably a bad idea anyway).

So how should we distribute scry?

1) Maintain brew taps and apt-get repos. Brew taps don't seem that hard to maintain, but I'm uncertain of the cost in effort for keeping an apt distribution. And that excludes arch and redhat linux users.

2) Build logic into Crystal-IDE to fetch proper version of scry (and detect updates). There's a lot of hidden effort here; like prompting users that an update is available, etc.

3) See if it's possible to make scry distributable as a development dependency. This is how, for example, rake is distributed most often to ruby projects. This would actually make the most sense, since you may need a different scry on different projects. However, I'm not certain that shards supports distributing binary dependencies in this way.

**Comment by timuckun** [comment]
I think brew would be the most logical way.

**Comment by faustinoaq** [comment]
I think that Scry distribution may be like [ruby-ide](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby) as a shard or a system package via AUR (Archlinux) or a .deb (Ubuntu/Debian).

For now, I'm using the default nodejs backend for crystal-ide, some errors aren't detected by scry.
But Scry is a great project, is the way to get IDE support for crystal with VScode (format, symbols, suggestions, references) 👌

**Comment by faustinoaq** [comment]
@kofno now VSCode size extension limit is 100MB :sweat_smile:

**Comment by faustinoaq** [comment]
Scry would be around `2.0Mb` :smile: 

`crystal build --release --no-debug -s src/scry.cr`

![screenshot_20170627_002416](https://user-images.githubusercontent.com/3067335/27572085-746587ae-5acf-11e7-9d37-f22396b3e59a.png)

**Comment by faustinoaq** [comment]
I tried to ship `scry.7z` in my extension and it's only **1.5Mb**

I think that with `win32` and `darwin` binaries the size could be less that **10Mb**

I'm using `node-7z` to extract scry:

```typescript
function extractScry(path) {
	return new Promise((resolve, reject) => {
		let unzip = new SevenZip()

		unzip.extractFull(path + '.7z', path.slice(0, -4)).progress((files) => {
			console.log('Extracting Scry files...')
		}).then(() => {
			console.log('Scry Extracting done!')
			resolve()
		}).catch((err) => {
			console.error(err)
			reject()
		});
	})
}
```

See [#L14](https://github.com/faustinoaq/vscode-crystal-lang/blob/support-scry/src/crystalMain.ts#L14)

**Comment by keplersj** [comment]
@faustinoaq Thanks for the shout out! I'd love to unify the efforts - especially since I only have time to work on things like this as weekend projects.

**Comment by faustinoaq** [comment]
@keplersj You're welcome, I'm still learning how Language Server Protocol works :sweat_smile:

**Comment by keplersj** [comment]
So here's my two-cents on this.

It sounds like the distribution strategy changes depending on the client and its needs. Sounds like VS Code wants the binary to come packaged with the client package, however Atom prefers you to have the client downloaded on its own separate from the initial package download and install.

I think the best solution would be to have this repo build and publish versioned binaries in archive files on the GitHub Releases page. Then clients can handle accordingly. VS Code packages could add a build step to download and incorporate into the final package, and Atom packages could access the archive directly.

@kofno and @faustinoaq: Let me know what y'all think of this strategy, I know how to implement this sort of thing using Travis.

**Comment by kofno** [comment]
I'm open for whatever. Would love to get this going again. I hate work stuff change my focus, but I'm really glad people are interested. If we can get some PRs going, maybe that's the best way to start a discussion.

**Comment by faustinoaq** [comment]
@keplersj I think you are right. I'm using Manjaro Linux, and I embedded Scry in my [extension](https://github.com/faustinoaq/vscode-crystal-lang#server-new) but is a bit hacky because it checks for extract Scry every time a crystal workspace is open.

Distributing the binaries would be a good way, so far I know, in ArchLinux we can use AUR and in Ubuntu a Launchpad repo, but I'm ok with a "releases" page on Github.

BTW:

I tried Scry on NeoVim and it works.

I think that completion goal, would be solved using [cracker](https://github.com/TechMagister/cracker) and embedding the crystal source with it inside Scry.

Some features like rename and symbols require some research to discover how implement them.

**Comment by keplersj** [comment]
@kofno If you're on board with the GitHub Releases strategy, could you set it up with your GitHub account when you get the chance? https://docs.travis-ci.com/user/deployment/releases/

**Comment by kofno** [comment]
@keplersj I like the idea. I will definitely set it up, but I'm hopping on a plane and I'm out of town for about 8 days. I don't think I'll be able to get that set up before I return.

**Comment by keplersj** [comment]
@kofno No worries!

**Comment by kofno** [comment]
I'm going to try and look at this over the weekend

**Comment by kofno** [comment]
@keplersj I've set up travis to do releases automatically. Were you going to take this the rest of the way, then? --> https://github.com/kofno/scry/commit/95aa5a332840b9592f6d5d1a0a52785284ca86e8

**Comment by keplersj** [comment]
![Can do!](https://media.giphy.com/media/evvVMQHAQZvNe/giphy.gif)
